services:
  postgres:
    image: postgres:15
    container_name: mcp-postgres
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: mcp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcp_user -d sampledb"]
      interval: 10s
      timeout: 5s
      retries: 5

  chatbot:
    build:
      context: ./mcp_chatbot
      dockerfile: Dockerfile
    environment:
      - OLLAMA_BASE_URL=http://192.168.69.35:11434
      - OLLAMA_MODEL=gemma3:12b
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mcp-network:
    driver: bridge